### ISSUE TITLE
[FEATURE] DiscordSRV integration

### ISSUE THREAD

**Issue by larssieboy18** [IdleBot-Development/IdleBot#25]
**Is your feature request related to a problem? Please describe.**
It is not really a bug or anything, but for 1 server, I now have 2 bots and people have to link twice.

**Describe the solution you'd like**
It would be great if Idlebot could integrate with DiscordSRV to make sure people get dm's/messages after they have used /discord link once.

**Comment by MetalTurtle18** [comment]
I agree this would be useful, and it's actually already in the planned features list. Can't tell when it will come but it will come!

**Comment by MetalTurtle18** [comment]
I am now working on this; it should be fully-functional within 1–2 weeks

**Comment by MetalTurtle18** [comment]
Hey @larssieboy18, 
Basic DiscordSRV integration has been added in the latest release. It isn't published to Spigot yet but you can download it [here](https://github.com/IdleBot-Development/IdleBot/releases/download/v1.2.0/IdleBot-1.2.0.jar). Please make a new issue if you find any bugs and we will try to fix them quickly. The wiki has not been updated yet, but I will add the new information soon and then publish to Spigot.
Thanks
