### ISSUE TITLE
[BUG] IdleBot enabling before DiscordSRV does

### ISSUE THREAD

**Issue by joex92** [IdleBot-Development/IdleBot#33]
The plugin is disabling itself because it's trying to enabled itself before DiscordSRV does:

```
16.06 04:02:53 [Server] INFO Enabling IdleBot v1.2.0
16.06 04:02:53 [Server] INFO Attempting to connect to DiscordSRV plugin
16.06 04:02:53 [Server] INFO DiscordSRV mode is enabled but the DiscordSRV plugin is not enabled. This could mean that it isn't installed or that something went wrong when loading it.
16.06 04:02:53 [Server] INFO Disabling IdleBot v1.2.0
16.06 04:02:53 [Server] INFO All data saved. Plugin safely closed!

```
as you can see here, DiscordSRV is enabled seconds after:
```
16.06 04:03:10 [Server] INFO Enabling DiscordSRV v1.23.0
```
I'm using other DiscordSRV addons as well and they are all being enabled after DiscordSRV is enabled...

**Comment by MetalTurtle18** [comment]
Hmm. It should wait since DiscordSRV is set as a soft dependency. I'll look into it.

**Comment by joex92** [comment]
any updates?

**Comment by MetalTurtle18** [comment]
Hey sorry I've been busy with other projects. I *will* look into it this week (hopefully also fix it).

**Comment by joex92** [comment]
oh ok, no prob... I thought that maybe you unintentionally forgot... 👍

**Comment by MetalTurtle18** [comment]
I think I should have a test build later today. @joex92 are you able to test a version before I release it to spigot later?

**Comment by MetalTurtle18** [comment]
[Here it is!](https://github.com/IdleBot-Development/IdleBot/releases/download/v1.2.1/IdleBot-1.2.1.jar) If you are unable to test in the next few days can you please let me know which plugins you were using that caused the issue so I can test it myself. Thanks

**Comment by joex92** [comment]
done
```
[14:44:46 INFO]: [DiscordSRV] Enabling DiscordSRV v1.23.0
[14:44:46 INFO]: [IdleBot] DiscordSRV plugin enabled. Starting communication
```
it works! thanks...
