### ISSUE TITLE
[BUG] Alerts happen only once in each category

### ISSUE THREAD

**Issue by doabell** [IdleBot-Development/IdleBot#35]
When AFKing, IdleBot only alerts the first event in each category (damage, x position, etc.) and ignores all subsequent events.

Especially when `afkmode` is set to `manual`, IdleBot only produces one alert per category (until `afk true` is explicitly set again), despite `/id info` showing `Set AFK: true`.

### To Reproduce
1.  Enter AFK mode manually
2.  Take Drowning Damage, then Falling Damage
3.  IdleBot only alerts Drowning Damage

### Expected behavior

IdleBot reports Drowning *and* Falling Damage

### Environment

- PaperMC 1.18.2 #387 [df630a2](https://github.com/PaperMC/Paper/commit/df630a27cc2d0b3731bf5dd311c4119c9c5b43f6) (latest)
- DiscordSRV [1.25.1](https://github.com/DiscordSRV/DiscordSRV/releases/tag/v1.25.1) (latest)
- IdleBot 1.2.1 (latest)

### Additional context
Happens in `afkmode auto` too - two attacks from the same player only produce one alert, even when they are more than `afktime` seconds apart.

I noticed this comment in [EventManager.java](https://github.com/IdleBot-Development/IdleBot/blob/aac9c00765770a1486f950e35d4b14aac5256dd1/src/main/java/io/github/idlebotdevelopment/idlebot/events/EventManager.java#L29):
> Lists to store the players who have already been pinged

If this is expected behavior, then would it be possible to make it configurable?
Something simple such as "a 5 second interval between messages" might already be very helpful. Thanks!

**Comment by MetalTurtle18** [comment]
You are correct that this is expected behavior. That sounds like a great configuration option. I'll add it to our list.

**Comment by MetalTurtle18** [comment]
This feature should be implemented now. Download the latest version: https://www.spigotmc.org/resources/idlebot-step-up-your-afk-game.88778/
